[profile.default]


src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    "@openzeppelin/contracts/=/home/bcdev/Downloads/project-bolt-sb1-sasdzuuz/Pacific-Trade-Hub/contracts/lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=/home/bcdev/Downloads/project-bolt-sb1-sasdzuuz/Pacific-Trade-Hub/contracts/lib/chainlink-brownie-contracts/contracts/src/v0.8/",
    "@chainlink/contracts-ccip/=/home/bcdev/Downloads/project-bolt-sb1-sasdzuuz/Pacific-Trade-Hub/contracts/lib/chainlink-brownie-contracts/contracts/src/v0.8/",
    "chainlink-brownie-contracts/=/home/bcdev/Downloads/project-bolt-sb1-sasdzuuz/Pacific-Trade-Hub/contracts/lib/chainlink-brownie-contracts/",
    "ds-test/=/home/bcdev/Downloads/project-bolt-sb1-sasdzuuz/Pacific-Trade-Hub/contracts/lib/openzeppelin-contracts/lib/forge-std/lib/ds-test/src/",
    "erc4626-tests/=/home/bcdev/Downloads/project-bolt-sb1-sasdzuuz/Pacific-Trade-Hub/contracts/lib/openzeppelin-contracts/lib/erc4626-tests/",
    "forge-std/=/home/bcdev/Downloads/project-bolt-sb1-sasdzuuz/Pacific-Trade-Hub/contracts/lib/forge-std/src/",
    "halmos-cheatcodes/=/home/bcdev/Downloads/project-bolt-sb1-sasdzuuz/Pacific-Trade-Hub/contracts/lib/openzeppelin-contracts/lib/halmos-cheatcodes/src/",
    "openzeppelin-contracts/=/home/bcdev/Downloads/project-bolt-sb1-sasdzuuz/Pacific-Trade-Hub/contracts/lib/openzeppelin-contracts/",

]
[rpc_endpoints]
amoy = "https://rpc-amoy.polygon.technology/"
